### ISSUE TITLE
Start button should go to settings

### ISSUE THREAD

**Issue by mpatterson16** [AugustanaCSC490Spring2020/HamRadioSimulator#15]
When you press start, it should go to the settings, not the game page.
Then from the settings there should be another start button that takes you to the game.
The parent activity of the settings activity should then be the main activity, not the game activity.

**Comment by thomasayele17** [comment]
> When you press start, it should go to the settings, not the game page.
> Then from the settings there should be another start button that takes you to the game.
> The parent activity of the settings activity should then be the main activity, not the game activity.

Made parent activity of settings activity, Main activity. 
Added a button in settings to start the game.
Start button also goes to the settings activity.

**Comment by mpatterson16** [comment]
The parent of the game activity is now the settings screen also, so I think we are done with this issue.
