### ISSUE TITLE
Call sign Firebase Storage 

### ISSUE THREAD

**Issue by mpatterson16** [AugustanaCSC490Spring2020/HamRadioSimulator#9]
- Fill database with call signs
- Query those call signs in the game activity

**Comment by thomasayele17** [comment]
Where can I find the list of call signs?

**Comment by mpatterson16** [comment]
Turn 1000 call signs into a text file and then read that file into a list that can be accessed in the app

**Comment by thomasayele17** [comment]
Added 1000 call signs into and text file and read that into an Array List.
